apiVersion: v1
kind: Service
metadata:
  name: mongo-master
  labels:
    app: example-3-db
    tier: db
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: example-3-db
    tier: db
