apiVersion: v1
kind: Service
metadata:
  name: example-2-frontend
  labels:
    app: example-2
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  
  selector:
    app: example-2
